name:                issue-blogger-killer
version:             0.1.0.0
github:              "y-usuzumi/issue-blogger-killer"
license:             BSD3
author:              "Yukio Usuzumi"
maintainer:          "anohigisavay@gmail.com"
copyright:           "2018 Yukio Usuzumi"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Stuff a repo with garbage issues

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- lens
- text
- wreq

library:
  source-dirs: src

default-extensions:
- RecordWildCards
- OverloadedStrings
- TypeFamilies

executables:
  issue-blogger-killer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - issue-blogger-killer

tests:
  issue-blogger-killer-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - issue-blogger-killer
